### ISSUE TITLE
Improve deploy github action

### ISSUE THREAD

**Issue by aminlatifi** [Giveth/impact-graph#1093] opened 2023-08-10 09:35 UTC
From `docker-compose up` help

```
If there are existing containers for a service, and the service's configuration
or image was changed after the container's creation, `docker-compose up` picks
up the changes by stopping and recreating the containers (preserving mounted
volumes). To prevent Compose from picking up changes, use the `--no-recreate`
flag.
```

I noticed today docker-compose up recreates dockers if they are updated. We, in our deploy actions, use to bring docker-compose configuration down and up again. Single up command will be enough and reduces downtime probably.

**Comment by MoeNick** [comment] 2023-08-16 11:48
Can devops make it happen?

**Comment by aminlatifi** [comment] 2023-08-21 11:24
> Can devops make it happen?

Yeah, not big change but good to be noticed

**Comment by mhmdksh** [comment] 2023-08-28 13:40
@aminlatifi Hey what is the exact problem?? Do you mean something is going wrong in the actions??

`docker-compose up -d` is intentional in our case in giveth-all deployment. In other words it's not a bug, it's a feature.

On the other hand, this is also meant to run as per service bases where it is necessary to pull the new images and recreate the container with the new image that is being pulled after a code push to github

**Comment by aminlatifi** [comment] 2023-08-28 13:44
> @aminlatifi Hey what is the exact problem?? Do you mean something is going wrong in the actions??
> 
> `docker-compose up -d` is intentional in our case in giveth-all deployment. In other words it's not a bug, it's a feature.
> 
> On the other hand, this is also meant to run as per service bases where it is necessary to pull the new images and recreate the container with the new image that is being pulled after a code push to github

I mean, the `docker-compose -f <docker-compose file> down` is not necessary. 
If we run the `pull` and `up -d` everything would be fine (it will recreate dockers with updated images) and we will have more service availability.

**Comment by mhmdksh** [comment] 2023-08-28 13:46
> > @aminlatifi Hey what is the exact problem?? Do you mean something is going wrong in the actions??
> > `docker-compose up -d` is intentional in our case in giveth-all deployment. In other words it's not a bug, it's a feature.
> > On the other hand, this is also meant to run as per service bases where it is necessary to pull the new images and recreate the container with the new image that is being pulled after a code push to github
> 
> I mean, the `docker-compose -f <docker-compose file> down` is not necessary. If we run the `pull` and `up -d` everything would be fine (it will recreate dockers with updated images) and we will have more service availability.

Yes, that's the normal behaviour, Thanks for the info man. We already took advantage of that in our giveth-all deployments :)

I think we can close this issue

**Comment by aminlatifi** [comment] 2023-08-28 14:39
> > > @aminlatifi Hey what is the exact problem?? Do you mean something is going wrong in the actions??
> > > `docker-compose up -d` is intentional in our case in giveth-all deployment. In other words it's not a bug, it's a feature.
> > > On the other hand, this is also meant to run as per service bases where it is necessary to pull the new images and recreate the container with the new image that is being pulled after a code push to github
> > 
> > 
> > I mean, the `docker-compose -f <docker-compose file> down` is not necessary. If we run the `pull` and `up -d` everything would be fine (it will recreate dockers with updated images) and we will have more service availability.
> 
> Yes, that's the normal behaviour, Thanks for the info man. We already took advantage of that in our giveth-all deployments :)
> 
> I think we can close this issue

But we still have `docker-compose stop impact-graph`  command
https://github.com/Giveth/impact-graph/blob/8568a898b16731906d232902e4f733c1b0211ed9/.github/workflows/staging-pipeline.yml#L137C33-L137C33

Is it needed?

**Comment by MoeNick** [comment] 2024-02-06 13:03
GM, can someone update me that is it still valid?

**Comment by mhmdksh** [comment] 2024-06-25 09:14
> > > > @aminlatifi Hey what is the exact problem?? Do you mean something is going wrong in the actions??
> > > > `docker-compose up -d` is intentional in our case in giveth-all deployment. In other words it's not a bug, it's a feature.
> > > > On the other hand, this is also meant to run as per service bases where it is necessary to pull the new images and recreate the container with the new image that is being pulled after a code push to github
> > > 
> > > 
> > > I mean, the `docker-compose -f <docker-compose file> down` is not necessary. If we run the `pull` and `up -d` everything would be fine (it will recreate dockers with updated images) and we will have more service availability.
> > 
> > 
> > Yes, that's the normal behaviour, Thanks for the info man. We already took advantage of that in our giveth-all deployments :)
> > I think we can close this issue
> 
> But we still have `docker-compose stop impact-graph` command https://github.com/Giveth/impact-graph/blob/8568a898b16731906d232902e4f733c1b0211ed9/.github/workflows/staging-pipeline.yml#L137C33-L137C33
> 
> Is it needed?

@aminlatifi Yes this is exactly what is needed.

@MoeNick @divine-comedian Please close this issue, our deployments are running and updating fine for more than a year now

**Closed as completed** 2024-06-25 16:27 UTC
