### ISSUE TITLE
Send Ortto Acitivity when a user completes their profile for the 1st time. 

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/impact-graph#1449] opened 2024-04-02 17:42 UTC
When a user completes their Giveth profile for the first time we would like to send them some onboarding emails in a journey. 

A new activity should be called in Ortto called `created-profile` when a user completes their profile for the first time - this activity is already setup in Ortto

sending a POST request to `https://api-us.ortto.app/v1/activities/create` it will have these fields: 

- email -  "str:cm:email":
- first name -  "str:cm:firstname"
- last name - "str:cm:lastname"
- userId - "str:cm:userid"

cc: @krmet

**Comment by RamRamez** [comment] 2024-04-02 19:50
I checked our user flow and I think the best solution for this is to call this new request when user fills their email address for the first time (email address changes from null to string)

**Comment by divine-comedian** [comment] 2024-04-17 15:56
@RamRamez  Great! That seem's fine, what are the next steps?

**Comment by RamRamez** [comment] 2024-05-05 12:49
@divine-comedian This is duplicate of https://github.com/Giveth/impact-graph/issues/1511
I think we can close this

**Closed as completed** 2024-05-06 06:15 UTC
Labels: p2
