### ISSUE TITLE
USD Value for old donations

### ISSUE THREAD

**Issue by MoeNick** [Giveth/impact-graph#278] opened 2021-12-26 14:21 UTC
> @mohammadranjbarz Mateo added Giv to monoswap yesterday so new donations should work now. However for old ones we must write the script, the script doesn't exist.
> 
> This will also be specially helpful for tokens that don't appear on monoswap, since we allow them now.
> 
> I lookup with Mateo some apis like coingecko (but this one is too limited, gotta pay to use effectively). But we should probably look a varios options that would work side by side monoswap library, and the script would run everyday to update those values.
> 
> Didn't write the script because we were unsure which api to use.

Thanks Carlos

@MoeNick  Should we create another story for what should we do for older donations?
( As Carlos said, I think it's not an easy or routine job, so it might need a little discussion as well)

_Originally posted by @mohammadranjbarz in https://github.com/Giveth/impact-graph/issues/276#issuecomment-1001190043_

**Comment by MoeNick** [comment] 2021-12-26 14:25
[Carlos comment](https://github.com/Giveth/impact-graph/issues/276#issuecomment-1001187052)

Mateo added Giv to monoswap yesterday so new donations should work now.
However for old ones we must write the script, the script doesn't exist.

This will also be specially helpful for tokens that don't appear on monoswap, since we allow them now.

I lookup with Mateo some apis like coingecko (but this one is too limited, gotta pay to use effectively). But we should probably look a varios options that would work side by side monoswap library, and the script would run everyday to update those values.

Didn't write the script because we were unsure which api to use.

**Comment by mohammadranjbarz** [comment] 2021-12-26 14:29
> [Carlos comment](https://github.com/Giveth/impact-graph/issues/276#issuecomment-1001187052)
> 
> Mateo added Giv to monoswap yesterday so new donations should work now. However for old ones we must write the script, the script doesn't exist.
> 
> This will also be specially helpful for tokens that don't appear on monoswap, since we allow them now.
> 
> I lookup with Mateo some apis like coingecko (but this one is too limited, gotta pay to use effectively). But we should probably look a varios options that would work side by side monoswap library, and the script would run everyday to update those values.
> 
> Didn't write the script because we were unsure which api to use.

I think we may change the title to **USD Value for old donations** 
because it's not limited to GIV donations, it may happen to all donations

**Comment by MoeNick** [comment] 2021-12-26 14:55
It's open for discussion guys, @mohammadranjbarz would u pls list our choices, what we should do?

**Comment by CarlosQ96** [comment] 2021-12-27 17:23
Honestly I think that for tokens that we don't support we should run a script to update them with other apis.
1. What service should we use? (In case it can't be added to our monoswap library).
2. When should the script run? (to avoid a price difference when we insert the values, OR I think we with the date with can get the price in a certain moment using the creation Date)

I double checked Coingecko with Mateo, free plan is 50 request in 1 minute. If we want more we gotta pay.
There should be other services but gotta investigate.

In the case of GIV, that was our mistake we forgot to add it to the monoswap instantly, so the script should also update old donations with GIV with monoswap succesfully.

**Comment by mohammadranjbarz** [comment] 2021-12-28 10:45
> Honestly I think that for tokens that we don't support we should run a script to update them with other apis.
> 
> 1. What service should we use? (In case it can't be added to our monoswap library).
> 2. When should the script run? (to avoid a price difference when we insert the values, OR I think we with the date with can get the price in a certain moment using the creation Date)
> 
> I double checked Coingecko with Mateo, free plan is 50 request in 1 minute. If we want more we gotta pay. There should be other services but gotta investigate.
> 
> In the case of GIV, that was our mistake we forgot to add it to the monoswap instantly, so the script should also update old donations with GIV with monoswap succesfully.

Thanks Carlos
Because the price is very important ( we calculate givback based on donation price) we should be sure that every donation has price, so I think this script is almost necessary to make sure that no donation is missed, but as you said we should check it to how to do it, 
does monoswap support price for othertimes  or just it get us price for Now time?
If we can use it in the cronjob script, it would be great, otherwise we should use something like coingecko ( And I think 50 request per minutes is enough)

**Comment by CarlosQ96** [comment] 2021-12-28 13:22
Monoswap only returns the current price. 
Coingecko can return the price history at a given date. HOWEVER, the issue is coingecko uses their internal ids to request tokens, we have to export first their token-ids to properly use the APIs thats the heavy part. (4k+ tokens) 
The file is huge, and even breaks their website hahaha Maybe we should export it to csv or something.

But after initial export that you can consult by history just fine.

Url: https://www.coingecko.com/es/api/documentation
@mohammadranjbarz

**Comment by mohammadranjbarz** [comment] 2021-12-28 13:25
> Monoswap only returns the current price. Coingecko can return the price history at a given date. HOWEVER, the issue is coingecko uses their internal ids to request tokens, we have to export first their token-ids to properly use the APIs thats the heavy part. (4k+ tokens) The file is huge, and even breaks their website hahaha Maybe we should export it to csv or something.
> 
> But after initial export that you can consult by history just fine.
> 
> Url: https://www.coingecko.com/es/api/documentation @mohammadranjbarz

@MoeNick  Do we support givbacks for all tokens are we just have a whitelist?
because for verifying donation I just check the token that are in our whitelist,
So @CarlosQ96  You can add coeingeckId of those donations  to this  list

https://github.com/Giveth/impact-graph/blob/staging/utils/tokenUtils.ts

that's not a long list and you can do it manually

**Comment by CarlosQ96** [comment] 2021-12-28 13:40
@mateodaza @divine-comedian @MoeNick There is one issue, we also now accept all tokens (erc20 at least). Most probably they aren't on our whitelist.
Should our script also try to update their usd/eth values? They can be some random obscure/new token haha

I think on the verification part, Mohammad would need to do something too.

**Comment by divine-comedian** [comment] 2021-12-28 14:28
it seems like since we're accepting any erc-20 token now the overhead of mainting the monoswap repo might become too time consuming - I think the idea of using the coingecko API will save us a lot of headaches going forward - let's see how much it will cost

 - the big problem is just as mohammad said that if we return no price for a donated token that has value or inaccurate price data there will be hell to pay if users begin to feel cheated.

**Comment by mateodaza** [comment] 2021-12-29 11:49
> @mateodaza @divine-comedian @MoeNick There is one issue, we also now accept all tokens (erc20 at least). Most probably they aren't on our whitelist. Should our script also try to update their usd/eth values? They can be some random obscure/new token haha
> 
> I think on the verification part, Mohammad would need to do something too.

I'd say if the price is found we save it, even if we do mistakes (let's say this obscure token is called the same as many)

We could run the script every 6 hours (or another rate) and check the price of missing tokens using the coingecko api, if the amount of tokens that we have to get price is greater than the api limit we put it on a job for a minute later. 

The steps could be something like

- Get all donations from a particular date (this is important as price must be date related) that need to get price right
- Get all tokens from those donations
- Check and save price from these tokens (once)
- Update donations with given price

First time running this script may be costly and could take a while historically. But if we set it up right it it may be just fine as this solution assumes we won't get many "obscure" "price unknown" tokens in a day

**Comment by divine-comedian** [comment] 2021-12-29 12:26
so this would still use monoswap and with any gaps in price data we fetch it from coingecko? and if we meter it out with a timed job as you say we wouldn't reach the rate limit. 

does this solution have any limitations if transaction volume on Giveth increases greatly? (10x)

**Comment by mohammadranjbarz** [comment] 2021-12-29 13:45
> so this would still use monoswap and with any gaps in price data we fetch it from coingecko? and if we meter it out with a timed job as you say we wouldn't reach the rate limit.
> 
> does this solution have any limitations if transaction volume on Giveth increases greatly? (10x)

Just we are not sure that history of prices are precise in coingecko ( you can test GIV price for few days ago, to see the prices are not accurate)

**Comment by MoeNick** [comment] 2021-12-30 12:29
Let's focus on this: How we can make sure we have a precise price history for missing transactions.

**Comment by WhyldWanderer** [comment] 2021-12-31 15:41
I remember that this tool was created by Giveth Social Coding team in the past... it could be helpful.
https://giveth.github.io/xchange-rates

**Comment by MoeNick** [comment] 2022-01-08 16:11
Would u pls update this issue guys?

**Comment by mohammadranjbarz** [comment] 2022-01-09 09:38
> Would u pls update this issue guys?

It seems all of old donations have usdValue

**Comment by MoeNick** [comment] 2022-01-10 16:18
We missed some GIV 2 trx from main net .

**Comment by divine-comedian** [comment] 2022-02-02 14:58
how can this issue be tested?

**Comment by mohammadranjbarz** [comment] 2022-02-04 05:30
> how can this issue be tested?

There should not be any **GIV** donation that doesn't have `usdValue`  and if you see in this screenshot the query return zero donations, so I think we can close this issue

<img width="1047" alt="Screen Shot 1400-11-15 at 09 00 01" src="https://user-images.githubusercontent.com/9850545/152477331-ac767137-cfcb-4028-a91a-823ce08d1091.png">

**Comment by divine-comedian** [comment] 2022-02-04 11:54
okay better question - how can I test this issue? Or how can it be moved to done?

**Comment by mohammadranjbarz** [comment] 2022-02-07 02:00
> okay better question - how can I test this issue? Or how can it be moved to done?

IMO you can move it to **done**, because the above query indicates that it works

**Closed as completed** 2022-09-07 10:47 UTC
