### ISSUE TITLE
Find and insert missing Polygon Donations 

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/impact-graph#1264] opened 2024-01-23 14:27 UTC
Based on Conversations we need to make sure no donations were missed from the Polygon round. 
**At the end of the round - January 25** 
For this we should:
- [ ]  run the subsquid service, find the potentially missed donations
- [ ]  compare against back-up service log to see if the donations are also not caught there
- [ ]  check transactions are valid donations 
- [ ]  write migration file to insert donations into DB

cc : @jainkrati @laurenluz

**Comment by laurenluz** [comment] 2024-01-23 16:49
the polygon round ends 11:59pm PT Jan 24 - FYI

**Comment by jainkrati** [comment] 2024-01-23 16:50
Based on today’s standup, we will have 
1. Short term solution: subsquid script which also adds pending transactions back to DB
2. Long term solution: fix the edge case issues of backup service after debugging root cause of missed backup scenarios

**Comment by MoeNick** [comment] 2024-02-05 10:06
Shall I close this? 
Im not sure who can do the QA?

**Comment by jainkrati** [comment] 2024-02-05 12:00
@laurenluz can we close this?

**Closed as completed** 2024-02-05 21:23 UTC
Labels: QF, p0
