### ISSUE TITLE
Some xdai donations status are failed in our DB

### ISSUE THREAD

**Issue by mohammadranjbarz** [Giveth/impact-graph#1030] opened 2023-06-15 12:58 UTC
As @WhyldWanderer  reported
> You can see the message in the support channel here [⁠💬┋support⁠ ](https://discord.com/channels/679428761438912522/835168432520429578/1118284296084521103)
Those donations are not even showing up on the project pages as far as I can tell.
Here are the transactions:
Dappnode: https://gnosisscan.io/tx/0xd7be75a75e41d7b1bfcf282dfd37bc7fd941f241c3b0ec35a4ec12096ba10bfb
Giveth Community of Makers: https://gnosisscan.io/tx/0x23007bbfdc358f147009024f41e01ac4873774d3861ed9ed39e09d0952b43aa5

**Comment by mohammadranjbarz** [comment] 2023-06-15 13:04
I checked and saw we have 7 donations with the same problem
<img width="1111" alt="Screen Shot 1402-03-25 at 11 58 06" src="https://github.com/Giveth/impact-graph/assets/9850545/b11dc786-af1d-411b-ba0c-eb34a76a8c6f">

as all donations were in xdai and the error message of donations I knew the problem is the symbol name of `xdai` token should have been **XDAI** but now it's **xDAI** in our DB so when verifying donation our system had thought it's a erc20 token transfer not a normal transfer and couldn't verify that, now I changed the token in the db, and also manually changed the status of those donations, and also I would make a hotfix and change it to not be case sensitive during this checking, 
but aside from that I have two ideas to know this problem sooner when it happens:
1. implementing a new endpoint in givback-calculation to show the unverified/.. donations filter by date, so each time before getting givback response , Ashley calls that endpoint check the donations and if she suspects any donation passes that to me or @CarlosQ96   to investigate it
2. When a donation fails in verification flow we send an error in a discord channel then it should notify us soon and we can know ASAP that there is a problem, so we can fix it sooner

@WhyldWanderer  @MoeNick  WDYT?

**Comment by WhyldWanderer** [comment] 2023-06-16 19:32
Thank you for investigating this Mohammad! Im glad you were able to find the cause.

I think that both of the things you suggested would be great to implement. Especially the warning in Discord. You may have to show me how to check the endpoint but I would be happy to do it each round as to not miss donations.

**Comment by laurenluz** [comment] 2023-07-24 15:13
should we close this?

**Comment by MoeNick** [comment] 2023-07-24 16:48
Warning in Discord should be implemented.

**Comment by divine-comedian** [comment] 2024-03-14 19:59
I think this one is fixed from the changes we made in pre-fetching the tx hash and the backup donation service.

**Closed as completed by divine-comedian** 2024-03-14 19:59 UTC
