### ISSUE TITLE
Review mutations  

### ISSUE THREAD

**Issue by MoeNick** [Giveth/impact-graph#304] opened 2022-01-17 17:42 UTC
investigating about missed donation

**Comment by CarlosQ96** [comment] 2022-01-26 15:38
@MoeNick I think the logs that we improved on a previous card are enough in terms of backend, we notify segment, save locally the log and send the error to frontend.

After lots of testing I did not find any issue with the backend saving donations.

I did a final test with @mateodaza today, regarding how it handles errors sent by the backend at it seems the issue is on the frontend. Even if there is an error it was still showing ok, when it shouldn't and not taking into account the status error code.

So Mateo is working on fixing that. After he fixes it it should complement what he did before regarding retrying donations.

**Comment by CarlosQ96** [comment] 2022-01-26 15:55
Moving to done with the findings documented. And creating a new card with the issue.

**Closed as completed** 2022-09-07 10:47 UTC
